/*
 * @Author: Peng Zeng
 * @Date: 2020-05-13 14:46:50
 * @Last Modified by: Peng Zeng
 * @Last Modified time: 2020-05-14 18:39:24
 */

// Fhasai's table
const DIAGNOSIS_GROUP_JSON = [
  {
    native_disease: "Aortic arch abnormal branching",
    native_disease_id: 1,
    groups: [
      {
        group_name: "Biventricular Aortic arch abnormal branching 1",
        prior_group: "",
        group_id: "1.1",
        codes: [
          ["Division of ligamentum"],
          ["Vascular ring repair"],
          ["Aberrant subclavian artery division or ligation"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Division of ligamentum",
      "Vascular ring repair",
      "Aberrant subclavian artery division or ligation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Coronary artery - Anomalous origin - From aorta - RCA from left",
    native_disease_id: 2,
    groups: [
      {
        group_name: "Biventricular Coronary artery - Anomalous origin - From aorta - RCA from left",
        prior_group: "",
        group_id: "2.1",
        codes: [["Anomalous aortic origin of coronary artery from aorta (AAOCA) repair"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "DILV",
    native_disease_id: 3,
    groups: [
      {
        group_name: NaN,
        prior_group: "",
        group_id: "3.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Palliative DILV 1",
        prior_group: "",
        group_id: "3.2",
        codes: [
          ["PDA enlargement"],
          ["Stage 1 palliation"],
          ["Systemic-to-pulmonary artery shunt"],
          ["Hybrid stage 1 palliation"],
          ["Bilateral pulmonary arterial banding"],
          ["Aortopulmonary anastomosis"],
          ["RV to PA conduit"],
        ],
        concomitant_procedures: ["IAA repair", "Aortic arch repair", "PDA closure"],
        subgroups: [
          {
            subgroup_name: "Sano:RV to PA conduit",
            codes: [["Sano:RV to PA conduit"]],
          },
          {
            subgroup_name: "BTS:Blalock-Taussig shunt",
            codes: [["BTS:Blalock-Taussig shunt"]],
          },
          {
            subgroup_name: "Hybrid",
            codes: [["Hybrid stage 1 palliation"]],
          },
        ],
      },
      {
        group_name: "1.5 ventricular repair DILV 1",
        prior_group: "",
        group_id: "3.3",
        codes: [["1.5 ventricle repair"], ["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement", "Pulmonary artery dilation"],
        subgroups: [],
      },
      {
        group_name: "Single ventricular repair DILV 1",
        prior_group: "",
        group_id: "3.4",
        codes: [["Fontan"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "PDA enlargement",
      "Stage 1 palliation",
      "Fontan",
      "Systemic-to-pulmonary artery shunt",
      "IAA repair",
      "Pulmonary artery dilation",
      "1.5 ventricle repair",
      "BTS:Blalock-Taussig shunt",
      "Hybrid stage 1 palliation",
      "Aortic arch repair",
      "Sano:RV to PA conduit",
      "Cavopulmonary anastomosis",
      "Bilateral pulmonary arterial banding",
      "PDA closure",
      "Aortopulmonary anastomosis",
      "RV to PA conduit",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "DCRV",
    native_disease_id: 4,
    groups: [
      {
        group_name: "Biventricular DCRV",
        prior_group: "",
        group_id: "4.1",
        codes: [["Moderator band resection"]],
        concomitant_procedures: ["RVOT reconstruction"],
        subgroups: [],
      },
    ],
    disease_related_procedures: ["Moderator band resection", "RVOT reconstruction"],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aorta - CoA - Moderate to severe",
    native_disease_id: 5,
    groups: [
      {
        group_name: "Biventricular repair-Aorta-CoA Moderate to severe 1",
        prior_group: "",
        group_id: "5.1",
        codes: [
          ["Coarctation procedure"],
          ["Aortic arch repair"],
          ["Coarctation procedure - Stent implantation"],
        ],
        concomitant_procedures: [
          "LVOT reconstruction",
          "VSD closure",
          "Mitral valvuloplasty",
          "Aortic valvuloplasty",
          "PDA closure",
        ],
        subgroups: [],
      },
      {
        group_name: "Cavopulmonary anastomosis--Aorta-CoA Moderate to severe ",
        prior_group: "",
        group_id: "5.2",
        codes: [["1.5 ventricle repair"], ["Cavopulmonary anastomosis"]],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Stage 1 palliation-Aorta-CoA Moderate to severe ",
        prior_group: "",
        group_id: "5.3",
        codes: [
          ["Stage 1 palliation"],
          ["Systemic-to-pulmonary artery shunt"],
          ["Hybrid stage 1 palliation"],
          ["Main pulmonary arterial banding"],
          ["Bilateral pulmonary arterial banding"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Coarctation procedure",
      "Stage 1 palliation",
      "LVOT reconstruction",
      "Systemic-to-pulmonary artery shunt",
      "1.5 ventricle repair",
      "Hybrid stage 1 palliation",
      "VSD closure",
      "Aortic arch repair",
      "PDA closure",
      "Cavopulmonary anastomosis",
      "Mitral valvuloplasty",
      "Main pulmonary arterial banding",
      "Bilateral pulmonary arterial banding",
      "Coarctation procedure - Stent implantation",
      "Aortic valvuloplasty",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aortic valve - AS - Moderate to severe",
    native_disease_id: 6,
    groups: [
      {
        group_name: "Biventricular Aortic valve-AS- Moderate to severe 1",
        prior_group: "",
        group_id: "6.1",
        codes: [
          ["Aortic valve replacement"],
          ["Aortic valve replacement - Using autologous pericardium (Ozaki)"],
          ["Ross procedure"],
          ["Aortic valvuloplasty"],
          ["Aortic annulus enlargment or augmentation"],
        ],
        concomitant_procedures: [
          "Mitral valvuloplasty",
          "PDA closure",
          "Ascending aortic replacement",
        ],
        subgroups: [],
      },
      {
        group_name: "Palliative Aortic valve-AS- Moderate to severe",
        prior_group: "",
        group_id: "6.2",
        codes: [
          ["Stage 1 palliation"],
          ["Aortopulmonary anastomosis"],
          ["Systemic-to-pulmonary artery shunt"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "1.5 ventricular repair Aortic valve-AS- Moderate to severe",
        prior_group: "",
        group_id: "6.3",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "Aortic valve replacement",
      "Stage 1 palliation",
      "Systemic-to-pulmonary artery shunt",
      "Aortic valve replacement - Using autologous pericardium (Ozaki)",
      "Ascending aortic replacement",
      "Ross procedure",
      "Cavopulmonary anastomosis",
      "Mitral valvuloplasty",
      "Aortic valvuloplasty",
      "Aortopulmonary anastomosis",
      "PDA closure",
      "Aortic annulus enlargment or augmentation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aorta - IAA",
    native_disease_id: 7,
    groups: [
      {
        group_name: "Biventricular Aorta-IAA 1",
        prior_group: "",
        group_id: "7.1",
        codes: [
          ["IAA repair"],
          ["Aortic arch repair"],
          ["Coarctation procedure - Stent implantation"],
        ],
        concomitant_procedures: [
          "LVOT reconstruction",
          "VSD closure",
          "Pulmonary artery reconstruction",
          "Mitral valvuloplasty",
          "Aortic valvuloplasty",
          "PDA closure",
          "Aortic annulus enlargment or augmentation",
        ],
        subgroups: [],
      },
      {
        group_name: "Palliative Aorta-IAA",
        prior_group: "",
        group_id: "7.2",
        codes: [["Main pulmonary arterial banding"], ["Aortopulmonary anastomosis"]],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "1.5 repair Aorta-IAA",
        prior_group: "",
        group_id: "7.3",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "LVOT reconstruction",
      "IAA repair",
      "VSD closure",
      "Pulmonary artery reconstruction",
      "Aortic arch repair",
      "PDA closure",
      "Cavopulmonary anastomosis",
      "Mitral valvuloplasty",
      "Main pulmonary arterial banding",
      "Aortopulmonary anastomosis",
      "Coarctation procedure - Stent implantation",
      "Aortic valvuloplasty",
      "Aortic annulus enlargment or augmentation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aortic valve - Dilated annulus",
    native_disease_id: 8,
    groups: [
      {
        group_name: "Biventricular Aortic valve-Dilated annulus 1",
        prior_group: "",
        group_id: "8.1",
        codes: [
          ["Ascending aortic replacement"],
          ["Aortic valvuloplasty"],
          ["Aortic root replacement"],
          ["Aortic valve replacement"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Ascending aortic replacement",
      "Aortic valvuloplasty",
      "Aortic root replacement",
      "Aortic valve replacement",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "TOF - PS",
    native_disease_id: 9,
    groups: [
      {
        group_name: "TOF PS repair 1",
        prior_group: "",
        group_id: "9.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["DORV repair"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "VSD enlargement or creation",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
          {
            subgroup_name: "Transanular patch",
            codes: [["Pulmonary transannular patch"]],
          },
          {
            subgroup_name: "Pulmoanry valve sparing repair",
            codes: [["Pulmoanry valve sparing repair"]],
          },
        ],
      },
      {
        group_name: "Palliative TOF PS 1",
        prior_group: "",
        group_id: "9.2",
        codes: [
          ["Unifocalization pulmonary artery and collaterals"],
          ["Main pulmonary arterial banding"],
          ["PDA enlargement"],
          ["Systemic-to-pulmonary artery shunt"],
        ],
        concomitant_procedures: [],
        subgroups: [
          {
            subgroup_name: "PDA balloon dilation",
            codes: [["PDA dilation"]],
          },
          {
            subgroup_name: "PDA stent implantation",
            codes: [["PDA stent implantation"]],
          },
        ],
      },
      {
        group_name: "TOF PS repair 2",
        prior_group: "Palliative TOF PS 1",
        group_id: "9.2.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["DORV repair"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "VSD enlargement or creation",
          "Pulmonary annulus enlargement",
          "Shunt closure",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
          {
            subgroup_name: "Transanular patch",
            codes: [["Pulmonary transannular patch"]],
          },
          {
            subgroup_name: "Pulmoanry valve sparing repair",
            codes: [["Pulmoanry valve sparing repair"]],
          },
        ],
      },
      {
        group_name: "Palliative TOF PS 2",
        prior_group: "Palliative TOF PS 1",
        group_id: "9.2.2",
        codes: [["Pulmonary artery dilation"], ["PDA enlargement"]],
        concomitant_procedures: [],
        subgroups: [
          {
            subgroup_name: "PDA balloon dilation",
            codes: [["PDA dilation"]],
          },
          {
            subgroup_name: "PDA stent implantation",
            codes: [["PDA stent implantation"]],
          },
        ],
      },
      {
        group_name: "Cavopulmonary anastomosis 1",
        prior_group: "Palliative TOF PS 1",
        group_id: "9.2.3",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
      {
        group_name: "Pulmonary valve replacement 1",
        prior_group: "TOF PS repair 1",
        group_id: "9.1.1",
        codes: [["Pulmonary valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Conduit replacement 1",
        prior_group: "TOF PS repair 1",
        group_id: "9.1.2",
        codes: [["Conduit replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Aortic valve replacement 1",
        prior_group: "TOF PS repair 1",
        group_id: "9.1.3",
        codes: [["Aortic valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Pulmonary valve replacement 1",
        prior_group: "TOF PS repair 2",
        group_id: "9.2.1.1",
        codes: [["Pulmonary valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Conduit replacement 1",
        prior_group: "TOF PS repair 2",
        group_id: "9.2.1.2",
        codes: [["Conduit replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Aortic valve replacement 1",
        prior_group: "TOF PS repair 2",
        group_id: "9.2.1.3",
        codes: [["Aortic valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "TOF PS repair 3",
        prior_group: "Palliative TOF PS 2",
        group_id: "9.2.2.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["DORV repair"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "VSD enlargement or creation",
          "Shunt closure",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
          {
            subgroup_name: "Transanular patch",
            codes: [["Pulmonary transannular patch"]],
          },
          {
            subgroup_name: "Pulmoanry valve sparing repair",
            codes: [["Pulmoanry valve sparing repair"]],
          },
        ],
      },
      {
        group_name: "Cavopulmonary anastomosis 2",
        prior_group: "Palliative TOF PS 2",
        group_id: "9.2.2.2",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
      {
        group_name: "Fontan",
        prior_group: "Cavopulmonary anastomosis 1",
        group_id: "9.2.3.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Fontan",
        prior_group: "Cavopulmonary anastomosis 2",
        group_id: "9.2.2.2.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Pulmonary transannular patch",
      "ASD creation or enlargement",
      "Conduit replacement",
      "Pulmonary annulus enlargement",
      "Systemic-to-pulmonary artery shunt",
      "TOF repair",
      "Pulmonary artery dilation",
      "DORV repair",
      "Pulmonary artery aneurysm resection",
      "VSD closure + RVOT reconstruction",
      "Shunt closure",
      "Unifocalization pulmonary artery and collaterals",
      "Collateral arterial division or ligation",
      "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
      "Main pulmonary arterial banding",
      "RV to PA conduit",
      "Interventricular fenestration",
      "PDA enlargement",
      "VSD enlargement or creation",
      "Pulmonary valve replacement",
      "PDA dilation",
      "PDA closure",
      "Pulmoanry valve sparing repair",
      "Cavopulmonary anastomosis",
      "Aortic valve replacement",
      "Tricuspid valvuloplasty",
      "Ventricular aneurysm resection",
      "PDA stent implantation",
      "VSD closure + Pulmonary valvuloplasty",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Double outlet atrium",
    native_disease_id: 10,
    groups: [
      {
        group_name: "Biventricular repair Double outlet atrium 1",
        prior_group: "",
        group_id: "10.1",
        codes: [["AVC repair"], ["Atrioventricular valvuloplasty"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: ["AVC repair", "Atrioventricular valvuloplasty"],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "AVC",
    native_disease_id: 11,
    groups: [
      {
        group_name: "Biventricular AVC 1",
        prior_group: "",
        group_id: "11.1",
        codes: [["AVC repair"]],
        concomitant_procedures: [
          "Mitral cleft suture",
          "PDA closure",
          "Atrioventricular valvuloplasty",
          "Tricuspid valvuloplasty",
          "Mitral valvuloplasty",
          "VSD closure",
        ],
        subgroups: [],
      },
      {
        group_name: "1.5 ventricle repair 1",
        prior_group: "",
        group_id: "11.2",
        codes: [["1.5 ventricle repair"], ["Cavopulmonary anastomosis"]],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Palliative AVC 1",
        prior_group: "",
        group_id: "11.3",
        codes: [["Main pulmonary arterial banding"], ["Systemic-to-pulmonary artery shunt"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Mitral cleft suture",
      "Systemic-to-pulmonary artery shunt",
      "Atrioventricular valvuloplasty",
      "Mitral valvuloplasty",
      "1.5 ventricle repair",
      "VSD closure",
      "Cavopulmonary anastomosis",
      "AVC repair",
      "Main pulmonary arterial banding",
      "Tricuspid valvuloplasty",
      "PDA closure",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Coronary artery - Anomalous origin - From aorta - LCA from right",
    native_disease_id: 12,
    groups: [
      {
        group_name:
          "Biventricular Coronary artery - Anomalous origin - From aorta - LCA from right 1",
        prior_group: "",
        group_id: "12.1",
        codes: [
          ["Anomalous aortic origin of coronary artery from aorta (AAOCA) repair"],
          ["Coronary artery bypass graft"],
          ["Coronary artery reimplantation"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
      "Coronary artery bypass graft",
      "Coronary artery reimplantation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aortic valve - Abnormal cusp",
    native_disease_id: 13,
    groups: [
      {
        group_name: "Aortic valve repair or replacement",
        prior_group: "",
        group_id: "13.1",
        codes: [
          ["Aortic valve replacement"],
          ["Aortic valve replacement - Using autologous pericardium (Ozaki)"],
          ["Ross procedure"],
          ["Aortic valvuloplasty"],
          ["Aortic annulus enlargment or augmentation"],
        ],
        concomitant_procedures: [
          "Mitral valvuloplasty",
          "PDA closure",
          "Ascending aortic replacement",
        ],
        subgroups: [],
      },
      {
        group_name: "Stage 1 palliation",
        prior_group: "",
        group_id: "13.2",
        codes: [["Stage 1 palliation"], ["Systemic-to-pulmonary artery shunt"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
      {
        group_name: "Glenn",
        prior_group: "",
        group_id: "13.3",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "Aortic valve replacement",
      "Stage 1 palliation",
      "Systemic-to-pulmonary artery shunt",
      "Aortic valve replacement - Using autologous pericardium (Ozaki)",
      "Ascending aortic replacement",
      "Ross procedure",
      "Cavopulmonary anastomosis",
      "Mitral valvuloplasty",
      "Aortic valvuloplasty",
      "PDA closure",
      "Aortic annulus enlargment or augmentation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "TOF - PA",
    native_disease_id: 14,
    groups: [
      {
        group_name: "TOF PA repair 1",
        prior_group: "",
        group_id: "14.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["DORV repair"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "VSD enlargement or creation",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
        ],
      },
      {
        group_name: "Palliative TOF PA 1",
        prior_group: "",
        group_id: "14.2",
        codes: [
          ["Unifocalization pulmonary artery and collaterals"],
          ["Main pulmonary arterial banding"],
          ["PDA enlargement"],
          ["Systemic-to-pulmonary artery shunt"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "TOF PA repair 2",
        prior_group: "Palliative TOF PA 1",
        group_id: "14.2.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["DORV repair"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "VSD enlargement or creation",
          "Pulmonary annulus enlargement",
          "Shunt closure",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
        ],
      },
      {
        group_name: "Palliative TOF PA 2",
        prior_group: "Palliative TOF PA 1",
        group_id: "14.2.2",
        codes: [["Pulmonary artery dilation"], ["PDA enlargement"]],
        concomitant_procedures: [],
        subgroups: [
          {
            subgroup_name: "PDA dilation",
            codes: [["PDA dilation"]],
          },
          {
            subgroup_name: "PDA stent implantation",
            codes: [["PDA stent implantation"]],
          },
        ],
      },
      {
        group_name: "Cavopulmonary anastomosis 1",
        prior_group: "Palliative TOF PA 1",
        group_id: "14.2.3",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
      {
        group_name: "Pulmonary valve replacement 1",
        prior_group: "TOF PA repair 1",
        group_id: "14.1.1",
        codes: [["Pulmonary valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Conduit replacement 1",
        prior_group: "TOF PA repair 1",
        group_id: "14.1.2",
        codes: [["Conduit replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Aortic valve replacement 1",
        prior_group: "TOF PA repair 1",
        group_id: "14.1.3",
        codes: [["Aortic valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Pulmonary valve replacement 1",
        prior_group: "TOF PA repair 2",
        group_id: "14.2.1.1",
        codes: [["Pulmonary valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Conduit replacement 1",
        prior_group: "TOF PA repair 2",
        group_id: "14.2.1.2",
        codes: [["Conduit replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Aortic valve replacement 1",
        prior_group: "TOF PA repair 2",
        group_id: "14.2.1.3",
        codes: [["Aortic valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "TOF PA repair 3",
        prior_group: "Palliative TOF PA 2",
        group_id: "14.2.2.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["DORV repair"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "VSD enlargement or creation",
          "Pulmonary annulus enlargement",
          "Shunt closure",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
        ],
      },
      {
        group_name: "Cavopulmonary anastomosis 2",
        prior_group: "Palliative TOF PA 2",
        group_id: "14.2.2.2",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
      {
        group_name: "Fontan",
        prior_group: "Cavopulmonary anastomosis 1",
        group_id: "14.2.3.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Fontan",
        prior_group: "Cavopulmonary anastomosis 2",
        group_id: "14.2.2.2.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "Conduit replacement",
      "Pulmonary annulus enlargement",
      "Systemic-to-pulmonary artery shunt",
      "TOF repair",
      "Pulmonary artery dilation",
      "DORV repair",
      "Pulmonary artery aneurysm resection",
      "VSD closure + RVOT reconstruction",
      "Shunt closure",
      "Unifocalization pulmonary artery and collaterals",
      "Collateral arterial division or ligation",
      "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
      "Main pulmonary arterial banding",
      "RV to PA conduit",
      "Interventricular fenestration",
      "PDA enlargement",
      "VSD enlargement or creation",
      "Pulmonary valve replacement",
      "PDA dilation",
      "PDA closure",
      "Cavopulmonary anastomosis",
      "Aortic valve replacement",
      "Tricuspid valvuloplasty",
      "Ventricular aneurysm resection",
      "PDA stent implantation",
      "VSD closure + Pulmonary valvuloplasty",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Ebstein's anomaly",
    native_disease_id: 15,
    groups: [
      {
        group_name: "Biventricular Ebstein's anomaly 1",
        prior_group: "",
        group_id: "15.1",
        codes: [["Tricuspid valvuloplasty"], ["Tricuspid valve replacement"]],
        concomitant_procedures: ["ASD closure"],
        subgroups: [],
      },
      {
        group_name: "1.5 ventricle repair Ebstein's anomaly 1",
        prior_group: "",
        group_id: "15.2",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
      {
        group_name: "Palliative Ebstein's anomaly 1",
        prior_group: "",
        group_id: "15.3",
        codes: [["Systemic-to-pulmonary artery shunt"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "Systemic-to-pulmonary artery shunt",
      "Tricuspid valve replacement",
      "Tricuspid valvuloplasty",
      "ASD closure",
      "Cavopulmonary anastomosis",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Mitral atresia",
    native_disease_id: 16,
    groups: [
      {
        group_name: NaN,
        prior_group: "",
        group_id: "16.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Stage 1Mitral atresia 1",
        prior_group: "",
        group_id: "16.2",
        codes: [
          ["Stage 1 palliation"],
          ["Systemic-to-pulmonary artery shunt"],
          ["Hybrid stage 1 palliation"],
          ["Bilateral pulmonary arterial banding"],
          ["Aortopulmonary anastomosis"],
          ["RV to PA conduit"],
        ],
        concomitant_procedures: [
          "ASD creation or enlargement",
          "Coarctation procedure",
          "Aortic arch repair",
        ],
        subgroups: [
          {
            subgroup_name: "Sano",
            codes: [["RV to PA conduit"]],
          },
          {
            subgroup_name: "Blalock-Taussig shunt",
            codes: [["Blalock-Taussig shunt"]],
          },
          {
            subgroup_name: "Hybrid",
            codes: [["Hybrid stage 1 palliation"]],
          },
        ],
      },
      {
        group_name: "1.5 ventricular repair Mitral atresia 1",
        prior_group: "",
        group_id: "16.3",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: [
          "ASD creation or enlargement",
          "Pulmonary artery ligation or division",
          "Pulmonary artery dilation",
          "Shunt closure",
          "Collateral arterial division or ligation",
          "Pulmonary artery reconstruction",
          "PDA closure",
        ],
        subgroups: [],
      },
      {
        group_name: "Single ventricular repair  Mitral atresia 1",
        prior_group: "",
        group_id: "16.4",
        codes: [["Fontan"], ["Fontan related procedure"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "Fontan",
      "Stage 1 palliation",
      "Pulmonary artery ligation or division",
      "Coarctation procedure",
      "Systemic-to-pulmonary artery shunt",
      "Pulmonary artery dilation",
      "Shunt closure",
      "Collateral arterial division or ligation",
      "Pulmonary artery reconstruction",
      "Bilateral pulmonary arterial banding",
      "RV to PA conduit",
      "Fontan related procedure",
      "Hybrid stage 1 palliation",
      "Aortic arch repair",
      "Cavopulmonary anastomosis",
      "Blalock-Taussig shunt",
      "Aortopulmonary anastomosis",
      "PDA closure",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "TOF",
    native_disease_id: 17,
    groups: [
      {
        group_name: "TOF repair 1",
        prior_group: "",
        group_id: "17.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["DORV repair"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "VSD enlargement or creation",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
          {
            subgroup_name: "Transanular patch",
            codes: [["Pulmonary transannular patch"]],
          },
          {
            subgroup_name: "Pulmoanry valve sparing repair",
            codes: [["Pulmoanry valve sparing repair"]],
          },
        ],
      },
      {
        group_name: "Palliative TOF 1",
        prior_group: "",
        group_id: "17.2",
        codes: [
          ["Unifocalization pulmonary artery and collaterals"],
          ["Main pulmonary arterial banding"],
          ["PDA enlargement"],
          ["Systemic-to-pulmonary artery shunt"],
        ],
        concomitant_procedures: [],
        subgroups: [
          {
            subgroup_name: "PDA balloon dilation",
            codes: [["PDA dilation"]],
          },
          {
            subgroup_name: "PDA stent implantation",
            codes: [["PDA stent implantation"]],
          },
        ],
      },
      {
        group_name: "TOF repair 2",
        prior_group: "Palliative TOF 1",
        group_id: "17.2.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["DORV repair"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "VSD enlargement or creation",
          "Shunt closure",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
          {
            subgroup_name: "Transanular patch",
            codes: [["Pulmonary transannular patch"]],
          },
          {
            subgroup_name: "Pulmoanry valve sparing repair",
            codes: [["Pulmoanry valve sparing repair"]],
          },
        ],
      },
      {
        group_name: "Palliative TOF 2",
        prior_group: "Palliative TOF 1",
        group_id: "17.2.2",
        codes: [["Pulmonary artery dilation"], ["PDA enlargement"]],
        concomitant_procedures: [],
        subgroups: [
          {
            subgroup_name: "PDA balloon dilation",
            codes: [["PDA dilation"]],
          },
          {
            subgroup_name: "PDA stent implantation",
            codes: [["PDA stent implantation"]],
          },
        ],
      },
      {
        group_name: "Cavopulmonary anastomosis 1",
        prior_group: "Palliative TOF 1",
        group_id: "17.2.3",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
      {
        group_name: "Pulmonary valve replacement 1",
        prior_group: "TOF repair 1",
        group_id: "17.1.1",
        codes: [["Pulmonary valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Conduit replacement 1",
        prior_group: "TOF repair 1",
        group_id: "17.1.2",
        codes: [["Conduit replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Aortic valve replacement 1",
        prior_group: "TOF repair 1",
        group_id: "17.1.3",
        codes: [["Aortic valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Pulmonary valve replacement 1",
        prior_group: "TOF repair 2",
        group_id: "17.2.1.1",
        codes: [["Pulmonary valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Conduit replacement 1",
        prior_group: "TOF repair 2",
        group_id: "17.2.1.2",
        codes: [["Conduit replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Aortic valve replacement 1",
        prior_group: "TOF repair 2",
        group_id: "17.2.1.3",
        codes: [["Aortic valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "TOF repair 3",
        prior_group: "Palliative TOF 2",
        group_id: "17.2.2.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["DORV repair"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "VSD enlargement or creation",
          "Shunt closure",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
          {
            subgroup_name: "Transanular patch",
            codes: [["Pulmonary transannular patch"]],
          },
          {
            subgroup_name: "Pulmoanry valve sparing repair",
            codes: [["Pulmoanry valve sparing repair"]],
          },
        ],
      },
      {
        group_name: "Cavopulmonary anastomosis 2",
        prior_group: "Palliative TOF 2",
        group_id: "17.2.2.2",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
      {
        group_name: "Fontan",
        prior_group: "Cavopulmonary anastomosis 1",
        group_id: "17.2.3.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Fontan",
        prior_group: "Cavopulmonary anastomosis 2",
        group_id: "17.2.2.2.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Pulmonary transannular patch",
      "ASD creation or enlargement",
      "Conduit replacement",
      "Systemic-to-pulmonary artery shunt",
      "TOF repair",
      "Pulmonary artery dilation",
      "DORV repair",
      "Pulmonary artery aneurysm resection",
      "VSD closure + RVOT reconstruction",
      "Shunt closure",
      "Unifocalization pulmonary artery and collaterals",
      "Collateral arterial division or ligation",
      "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
      "Main pulmonary arterial banding",
      "RV to PA conduit",
      "Interventricular fenestration",
      "PDA enlargement",
      "VSD enlargement or creation",
      "Pulmonary valve replacement",
      "PDA dilation",
      "PDA closure",
      "Pulmoanry valve sparing repair",
      "Cavopulmonary anastomosis",
      "Aortic valve replacement",
      "Tricuspid valvuloplasty",
      "Ventricular aneurysm resection",
      "PDA stent implantation",
      "VSD closure + Pulmonary valvuloplasty",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "HLHS",
    native_disease_id: 18,
    groups: [
      {
        group_name: "Biventricular repair HLHS 1",
        prior_group: "",
        group_id: "18.1",
        codes: [["Aortic valvuloplasty"]],
        concomitant_procedures: ["Mitral valvuloplasty"],
        subgroups: [],
      },
      {
        group_name: "Stage 1 HLHS 1",
        prior_group: "",
        group_id: "18.2",
        codes: [
          ["Stage 1 palliation"],
          ["Systemic-to-pulmonary artery shunt"],
          ["Hybrid stage 1 palliation"],
          ["Bilateral pulmonary arterial banding"],
          ["Aortopulmonary anastomosis"],
          ["RV to PA conduit"],
        ],
        concomitant_procedures: ["Coarctation procedure", "Aortic arch repair"],
        subgroups: [
          {
            subgroup_name: "Sano:RV to PA conduit",
            codes: [["Sano:RV to PA conduit"]],
          },
          {
            subgroup_name: "BTS:Blalock-Taussig shunt",
            codes: [["BTS:Blalock-Taussig shunt"]],
          },
          {
            subgroup_name: "Hybrid",
            codes: [["Hybrid stage 1 palliation"]],
          },
        ],
      },
      {
        group_name: "1.5 ventricular repair HLHS 1",
        prior_group: "",
        group_id: "18.3",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: [
          "ASD creation or enlargement",
          "Pulmonary artery dilation",
          "Shunt closure",
          "Collateral arterial division or ligation",
          "PDA closure",
        ],
        subgroups: [],
      },
      {
        group_name: "Single ventricular repair  HLHS 1",
        prior_group: "",
        group_id: "18.4",
        codes: [["Fontan"], ["Fontan related procedure"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "Fontan",
      "Stage 1 palliation",
      "Coarctation procedure",
      "Systemic-to-pulmonary artery shunt",
      "Pulmonary artery dilation",
      "Shunt closure",
      "Collateral arterial division or ligation",
      "Sano:RV to PA conduit",
      "Mitral valvuloplasty",
      "Bilateral pulmonary arterial banding",
      "BTS:Blalock-Taussig shunt",
      "RV to PA conduit",
      "Fontan related procedure",
      "Hybrid stage 1 palliation",
      "Aortic arch repair",
      "Cavopulmonary anastomosis",
      "Aortic valvuloplasty",
      "Aortopulmonary anastomosis",
      "PDA closure",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Atrium-Divided RA( Cor triatriatum dexter)",
    native_disease_id: 19,
    groups: [
      {
        group_name: "Biventricular Atrium-Divided RA( Cor triatriatum dexter)1",
        prior_group: "",
        group_id: "19.1",
        codes: [["Cor triatriatum resection"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: ["Cor triatriatum resection"],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "PAIVS",
    native_disease_id: 20,
    groups: [
      {
        group_name: "Biventricular PA IVS 1",
        prior_group: "",
        group_id: "20.1",
        codes: [["RVOT reconstruction"], ["Pulmonary valvuloplasty"]],
        concomitant_procedures: ["Collateral arterial division or ligation", "PDA closure"],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
          {
            subgroup_name: "Transanular patch",
            codes: [["Pulmonary transannular patch"]],
          },
        ],
      },
      {
        group_name: "1.5 ventricle repair PA IVS 1",
        prior_group: "",
        group_id: "20.2",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: [
          "ASD creation or enlargement",
          "Pulmonary artery ligation or division",
        ],
        subgroups: [],
      },
      {
        group_name: "Palliative PA IVS 1",
        prior_group: "",
        group_id: "20.3",
        codes: [
          ["Unifocalization pulmonary artery and collaterals"],
          ["PDA enlargement"],
          ["Systemic-to-pulmonary artery shunt"],
        ],
        concomitant_procedures: [],
        subgroups: [
          {
            subgroup_name: "PDA dilation",
            codes: [["PDA dilation"]],
          },
          {
            subgroup_name: "PDA stent implantation",
            codes: [["PDA stent implantation"]],
          },
        ],
      },
    ],
    disease_related_procedures: [
      "Pulmonary transannular patch",
      "PDA enlargement",
      "ASD creation or enlargement",
      "Pulmonary valvuloplasty",
      "Pulmonary artery ligation or division",
      "Systemic-to-pulmonary artery shunt",
      "PDA dilation",
      "Unifocalization pulmonary artery and collaterals",
      "Collateral arterial division or ligation",
      "Cavopulmonary anastomosis",
      "RVOT reconstruction",
      "PDA closure",
      "PDA stent implantation",
      "RV to PA conduit",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Coronary artery - Anomalous origin - From aorta - Others",
    native_disease_id: 21,
    groups: [
      {
        group_name: "Biventricular Coronary artery - Anomalous origin - From aorta - Others",
        prior_group: "",
        group_id: "21.1",
        codes: [
          ["Anomalous aortic origin of coronary artery from aorta (AAOCA) repair"],
          ["Coronary artery reimplantation"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
      "Coronary artery reimplantation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Coronary artery - Coronary fistula",
    native_disease_id: 22,
    groups: [
      {
        group_name: "Biventricular Coronary artery - Coronary fistula",
        prior_group: "",
        group_id: "22.1",
        codes: [
          ["Arterio-venous fistula procedure - Ligation or closure"],
          ["Coronary cameral fistula procedure"],
          ["Coronary artery reimplantation"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Arterio-venous fistula procedure - Ligation or closure",
      "Coronary cameral fistula procedure",
      "Coronary artery reimplantation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Coronary artery - Anomalous origin - From PA",
    native_disease_id: 23,
    groups: [
      {
        group_name: "Biventricular Coronary artery - Anomalous origin - From PA",
        prior_group: "",
        group_id: "23.1",
        codes: [
          ["Anomalous coronary artery from pulmonary artery repair"],
          ["Coronary artery bypass graft"],
          ["Coronary artery reimplantation"],
          ["Takeuchi procedure"],
          ["Anomalous aortic origin of coronary artery from aorta (AAOCA) repair"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
      "Anomalous coronary artery from pulmonary artery repair",
      "Coronary artery bypass graft",
      "Coronary artery reimplantation",
      "Takeuchi procedure",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aortic valve-Prolapse",
    native_disease_id: 24,
    groups: [
      {
        group_name: "Biventricular Aortic valve-Prolapse 1",
        prior_group: "",
        group_id: "24.1",
        codes: [["Aortic valvuloplasty"], ["Aortic valve replacement"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: ["Aortic valvuloplasty", "Aortic valve replacement"],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Coronary artery - Anomalous course - Intramural",
    native_disease_id: 25,
    groups: [
      {
        group_name: "Biventricular Coronary artery - Anomalous course - Intramural 1",
        prior_group: "",
        group_id: "25.1",
        codes: [
          ["Anomalous aortic origin of coronary artery from aorta (AAOCA) repair"],
          ["Coronary artery reimplantation"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
      "Coronary artery reimplantation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aorta - Vascular ring",
    native_disease_id: 26,
    groups: [
      {
        group_name: "Biventricular Aorta-Vascular ring1",
        prior_group: "",
        group_id: "26.1",
        codes: [
          ["Division of ligamentum"],
          ["Double aortic arch procedure"],
          ["Vascular ring repair"],
          ["Aberrant subclavian artery division or ligation"],
        ],
        concomitant_procedures: ["PDA closure"],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Division of ligamentum",
      "Double aortic arch procedure",
      "PDA closure",
      "Vascular ring repair",
      "Aberrant subclavian artery division or ligation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Coronary artery - Anomalous branching",
    native_disease_id: 27,
    groups: [
      {
        group_name: "Biventricular Coronary artery - Anomalous branching 1",
        prior_group: "",
        group_id: "27.1",
        codes: [
          ["Anomalous aortic origin of coronary artery from aorta (AAOCA) repair"],
          ["Coronary artery reimplantation"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
      "Coronary artery reimplantation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "TOF - AVC",
    native_disease_id: 28,
    groups: [
      {
        group_name: "TOF AVC repair 1",
        prior_group: "",
        group_id: "28.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "Mitral cleft suture",
          "VSD enlargement or creation",
          "Moderator band resection",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "Pulmonary artery reconstruction",
          "AVC repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
          {
            subgroup_name: "Transanular patch",
            codes: [["Pulmonary transannular patch"]],
          },
          {
            subgroup_name: "Pulmoanry valve sparing repair",
            codes: [["Pulmoanry valve sparing repair"]],
          },
        ],
      },
      {
        group_name: "Palliative TOF AVC 1",
        prior_group: "",
        group_id: "28.2",
        codes: [
          ["Main pulmonary arterial banding"],
          ["PDA enlargement"],
          ["Systemic-to-pulmonary artery shunt"],
        ],
        concomitant_procedures: [],
        subgroups: [
          {
            subgroup_name: "PDA balloon dilation",
            codes: [["PDA dilation"]],
          },
          {
            subgroup_name: "PDA stent implantation",
            codes: [["PDA stent implantation"]],
          },
        ],
      },
      {
        group_name: "TOF AVC repair 2",
        prior_group: "Palliative TOF AVC 1",
        group_id: "28.2.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "Mitral cleft suture",
          "VSD enlargement or creation",
          "Pulmonary annulus enlargement",
          "Moderator band resection",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "Pulmonary artery reconstruction",
          "AVC repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
          {
            subgroup_name: "Transanular patch",
            codes: [["Pulmonary transannular patch"]],
          },
          {
            subgroup_name: "Pulmoanry valve sparing repair",
            codes: [["Pulmoanry valve sparing repair"]],
          },
        ],
      },
      {
        group_name: "Palliative TOF AVC 2",
        prior_group: "Palliative TOF AVC 1",
        group_id: "28.2.2",
        codes: [["Pulmonary artery dilation"], ["PDA enlargement"]],
        concomitant_procedures: [],
        subgroups: [
          {
            subgroup_name: "PDA dilation",
            codes: [["PDA dilation"]],
          },
          {
            subgroup_name: "PDA stent implantation",
            codes: [["PDA stent implantation"]],
          },
        ],
      },
      {
        group_name: "Cavopulmonary anastomosis 1",
        prior_group: "Palliative TOF AVC 1",
        group_id: "28.2.3",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
      {
        group_name: "Pulmonary valve replacement 1",
        prior_group: "TOF AVC repair 1",
        group_id: "28.1.1",
        codes: [["Pulmonary valve replacement"]],
        concomitant_procedures: [
          "Mitral valve replacement",
          "Pulmonary artery aneurysm resection",
          "VSD closure",
          "Mitral valvuloplasty",
          "Tricuspid valvuloplasty",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Conduit replacement 1",
        prior_group: "TOF AVC repair 1",
        group_id: "28.1.2",
        codes: [["Conduit replacement"]],
        concomitant_procedures: [
          "Mitral valve replacement",
          "Pulmonary artery aneurysm resection",
          "Mitral valvuloplasty",
          "Tricuspid valvuloplasty",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Pulmonary valve replacement 1",
        prior_group: "TOF AVC repair 2",
        group_id: "28.2.1.1",
        codes: [["Pulmonary valve replacement"]],
        concomitant_procedures: [
          "Mitral valve replacement",
          "Pulmonary artery aneurysm resection",
          "VSD closure",
          "Mitral valvuloplasty",
          "Tricuspid valvuloplasty",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Conduit replacement 1",
        prior_group: "TOF AVC repair 2",
        group_id: "28.2.1.2",
        codes: [["Conduit replacement"]],
        concomitant_procedures: [
          "Mitral valve replacement",
          "Pulmonary artery aneurysm resection",
          "VSD closure",
          "Mitral valvuloplasty",
          "Tricuspid valvuloplasty",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "TOF AVC repair 3",
        prior_group: "Palliative TOF AVC 2",
        group_id: "28.2.2.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "Mitral cleft suture",
          "VSD enlargement or creation",
          "Moderator band resection",
          "Collateral arterial division or ligation",
          "Unifocalization pulmonary artery and collaterals",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "Pulmonary artery reconstruction",
          "AVC repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
          {
            subgroup_name: "Transanular patch",
            codes: [["Pulmonary transannular patch"]],
          },
          {
            subgroup_name: "Pulmoanry valve sparing repair",
            codes: [["Pulmoanry valve sparing repair"]],
          },
        ],
      },
      {
        group_name: "Cavopulmonary anastomosis 2",
        prior_group: "Palliative TOF AVC 2",
        group_id: "28.2.2.2",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
      {
        group_name: "Fontan",
        prior_group: "Cavopulmonary anastomosis 1",
        group_id: "28.2.3.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Fontan",
        prior_group: "Cavopulmonary anastomosis 2",
        group_id: "28.2.2.2.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Pulmonary annulus enlargement",
      "Pulmonary artery dilation",
      "Pulmonary artery aneurysm resection",
      "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
      "Pulmonary artery reconstruction",
      "RV to PA conduit",
      "PDA enlargement",
      "PDA dilation",
      "Tricuspid valvuloplasty",
      "VSD closure",
      "PDA stent implantation",
      "Ventricular aneurysm resection",
      "PDA closure",
      "Pulmonary transannular patch",
      "Mitral cleft suture",
      "Conduit replacement",
      "ASD creation or enlargement",
      "Systemic-to-pulmonary artery shunt",
      "TOF repair",
      "Mitral valve replacement",
      "Collateral arterial division or ligation",
      "Unifocalization pulmonary artery and collaterals",
      "AVC repair",
      "Main pulmonary arterial banding",
      "Mitral valvuloplasty",
      "Interventricular fenestration",
      "VSD enlargement or creation",
      "Pulmonary valve replacement",
      "Moderator band resection",
      "Pulmoanry valve sparing repair",
      "Cavopulmonary anastomosis",
      "VSD closure + RVOT reconstruction",
      "VSD closure + Pulmonary valvuloplasty",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aortic valve - Hypoplastic annulus",
    native_disease_id: 29,
    groups: [
      {
        group_name: "Biventricular Aortic valve-Hypoplastic annulus 1",
        prior_group: "",
        group_id: "29.1",
        codes: [
          ["Aortic valvuloplasty"],
          ["Aortic valve replacement"],
          ["Aortic annulus enlargment or augmentation"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Palliative Aortic valve-Hypoplastic annulus 1",
        prior_group: "",
        group_id: "29.2",
        codes: [["Stage 1 palliation"], ["Systemic-to-pulmonary artery shunt"]],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "1.5 ventricular repair Aortic valve-Hypoplastic annulus",
        prior_group: "",
        group_id: "29.3",
        codes: [],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "Stage 1 palliation",
      "Systemic-to-pulmonary artery shunt",
      "Aortic valve replacement",
      "Aortic valvuloplasty",
      "Aortic annulus enlargment or augmentation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Cor triatriatum",
    native_disease_id: 30,
    groups: [
      {
        group_name: "Biventricular Cor triatriatum1",
        prior_group: "",
        group_id: "30.1",
        codes: [["Cor triatriatum resection"]],
        concomitant_procedures: ["PAPVC repair", "ASD closure"],
        subgroups: [],
      },
    ],
    disease_related_procedures: ["PAPVC repair", "ASD closure", "Cor triatriatum resection"],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aortic valve - Atresia",
    native_disease_id: 31,
    groups: [
      {
        group_name: "Biventricular Aortic valve-AS 1",
        prior_group: "",
        group_id: "31.1",
        codes: [["Yasui procedure"]],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Palliative Aortic valve-AS- Moderate to severe",
        prior_group: "",
        group_id: "31.2",
        codes: [
          ["Stage 1 palliation"],
          ["Aortopulmonary anastomosis"],
          ["Systemic-to-pulmonary artery shunt"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "1.5 ventricular repair Aortic valve-AS- Moderate to severe",
        prior_group: "",
        group_id: "31.3",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "Stage 1 palliation",
      "Systemic-to-pulmonary artery shunt",
      "Cavopulmonary anastomosis",
      "Aortopulmonary anastomosis",
      "Yasui procedure",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Hemitruncus",
    native_disease_id: 32,
    groups: [
      {
        group_name: "Biventricular repair Hemitruncus 1",
        prior_group: "",
        group_id: "32.1",
        codes: [
          ["Truncus arteriosus repair"],
          ["Pulmonary artery reimplantation or reconnection"],
          ["RV to PA conduit"],
        ],
        concomitant_procedures: [
          "VSD closure",
          "RVOT reconstruction",
          "PDA closure",
          "Pulmonary artery reconstruction",
        ],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "PDA closure",
      "Pulmonary artery reimplantation or reconnection",
      "Truncus arteriosus repair",
      "Pulmonary artery reconstruction",
      "RVOT reconstruction",
      "VSD closure",
      "RV to PA conduit",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aortic valve - AS",
    native_disease_id: 33,
    groups: [
      {
        group_name: "Biventricular Aortic valve-AS 1",
        prior_group: "",
        group_id: "33.1",
        codes: [
          ["Aortic valve replacement"],
          ["LVOT reconstruction"],
          ["Aortic valve replacement - Using autologous pericardium (Ozaki)"],
          ["Ross procedure"],
          ["Aortic valvuloplasty"],
          ["Aortic annulus enlargment or augmentation"],
        ],
        concomitant_procedures: [
          "Mitral valvuloplasty",
          "PDA closure",
          "Ascending aortic replacement",
        ],
        subgroups: [],
      },
      {
        group_name: "Palliative Aortic valve-AS- Moderate to severe",
        prior_group: "",
        group_id: "33.2",
        codes: [
          ["Stage 1 palliation"],
          ["Aortopulmonary anastomosis"],
          ["Systemic-to-pulmonary artery shunt"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "1.5 ventricular repair Aortic valve-AS- Moderate to severe",
        prior_group: "",
        group_id: "33.3",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: ["ASD creation or enlargement"],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "Aortic valve replacement",
      "Stage 1 palliation",
      "LVOT reconstruction",
      "Systemic-to-pulmonary artery shunt",
      "Aortic valve replacement - Using autologous pericardium (Ozaki)",
      "Ascending aortic replacement",
      "Ross procedure",
      "Cavopulmonary anastomosis",
      "Mitral valvuloplasty",
      "Aortic valvuloplasty",
      "Aortopulmonary anastomosis",
      "PDA closure",
      "Aortic annulus enlargment or augmentation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "AP window",
    native_disease_id: 34,
    groups: [
      {
        group_name: "Biventricular AP window 1",
        prior_group: "",
        group_id: "34.1",
        codes: [["AP window repair"]],
        concomitant_procedures: ["ASD closure", "VSD closure"],
        subgroups: [],
      },
      {
        group_name: "Palliative AP window 1",
        prior_group: "",
        group_id: "34.2",
        codes: [["Bilateral pulmonary arterial banding"], ["Branch pulmonary arterial banding"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "AP window repair",
      "ASD closure",
      "Bilateral pulmonary arterial banding",
      "VSD closure",
      "Branch pulmonary arterial banding",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "TOF - Absent pulmonary valve syndrome",
    native_disease_id: 35,
    groups: [
      {
        group_name: "TOF-Absent pulmonary valve syndrome repair 1",
        prior_group: "",
        group_id: "35.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["DORV repair"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "VSD enlargement or creation",
          "Pulmonary artery aneurysm resection",
          "Moderator band resection",
          "Pulmonary artery plication",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
        ],
      },
      {
        group_name: "Palliative TOF-Absent pulmonary valve syndrome PA 1",
        prior_group: "",
        group_id: "35.2",
        codes: [["Systemic-to-pulmonary artery shunt"]],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "TOF-Absent pulmonary valve syndrome repair 2",
        prior_group: "Palliative TOF-Absent pulmonary valve syndrome PA 1",
        group_id: "35.2.1",
        codes: [
          ["VSD closure", "RVOT reconstruction"],
          ["DORV repair"],
          ["VSD closure", "Pulmonary valvuloplasty"],
          ["TOF repair"],
        ],
        concomitant_procedures: [
          "VSD enlargement or creation",
          "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
          "PDA closure",
          "Interventricular fenestration",
        ],
        subgroups: [
          {
            subgroup_name: "RV to PA conduit",
            codes: [["RV to PA conduit"]],
          },
        ],
      },
      {
        group_name: "Cavopulmonary anastomosis 1",
        prior_group: "Palliative TOF-Absent pulmonary valve syndrome PA 1",
        group_id: "35.2.2",
        codes: [["Cavopulmonary anastomosis"]],
        concomitant_procedures: [
          "Pulmonary artery aneurysm resection",
          "Moderator band resection",
          "Pulmonary artery plication",
        ],
        subgroups: [],
      },
      {
        group_name: "Pulmonary valve replacement 1",
        prior_group: "TOF-Absent pulmonary valve syndrome repair 1",
        group_id: "35.1.1",
        codes: [["Pulmonary valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Conduit replacement 1",
        prior_group: "TOF-Absent pulmonary valve syndrome repair 1",
        group_id: "35.1.2",
        codes: [["Conduit replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Valved conduit insertion 1",
        prior_group: "TOF-Absent pulmonary valve syndrome repair 1",
        group_id: "35.1.3",
        codes: [["Valved conduit insertion"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Pulmonary valve replacement 1",
        prior_group: "TOF-Absent pulmonary valve syndrome repair 2",
        group_id: "35.2.1.1",
        codes: [["Pulmonary valve replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Conduit replacement 1",
        prior_group: "TOF-Absent pulmonary valve syndrome repair 2",
        group_id: "35.2.1.2",
        codes: [["Conduit replacement"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Valved conduit insertion 1",
        prior_group: "TOF-Absent pulmonary valve syndrome repair 2",
        group_id: "35.2.1.3",
        codes: [["Valved conduit insertion"]],
        concomitant_procedures: [
          "Tricuspid valvuloplasty",
          "Pulmonary artery aneurysm resection",
          "Ventricular aneurysm resection",
        ],
        subgroups: [],
      },
      {
        group_name: "Fontan",
        prior_group: "Cavopulmonary anastomosis 1",
        group_id: "35.2.2.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Conduit replacement",
      "Systemic-to-pulmonary artery shunt",
      "TOF repair",
      "DORV repair",
      "Pulmonary artery aneurysm resection",
      "Pulmonary artery plication",
      "Anomalous aortic origin of coronary artery from aorta (AAOCA) repair",
      "RV to PA conduit",
      "Interventricular fenestration",
      "VSD enlargement or creation",
      "Pulmonary valve replacement",
      "Moderator band resection",
      "Valved conduit insertion",
      "PDA closure",
      "Cavopulmonary anastomosis",
      "VSD closure + RVOT reconstruction",
      "Tricuspid valvuloplasty",
      "Ventricular aneurysm resection",
      "VSD closure + Pulmonary valvuloplasty",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "DIRV",
    native_disease_id: 36,
    groups: [
      {
        group_name: NaN,
        prior_group: "",
        group_id: "36.1",
        codes: [],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Palliative DIRV 1",
        prior_group: "",
        group_id: "36.2",
        codes: [
          ["Stage 1 palliation"],
          ["Systemic-to-pulmonary artery shunt"],
          ["Hybrid stage 1 palliation"],
          ["Main pulmonary arterial banding"],
          ["Bilateral pulmonary arterial banding"],
          ["Aortopulmonary anastomosis"],
          ["RV to PA conduit"],
        ],
        concomitant_procedures: [
          "IAA repair",
          "Aortic arch repair",
          "PDA closure",
          "RV to PA conduit",
        ],
        subgroups: [
          {
            subgroup_name: "Sano:RV to PA conduit",
            codes: [["Sano:RV to PA conduit"]],
          },
          {
            subgroup_name: "BTS:Blalock-Taussig shunt",
            codes: [["BTS:Blalock-Taussig shunt"]],
          },
          {
            subgroup_name: "Hybrid",
            codes: [["Hybrid stage 1 palliation"]],
          },
        ],
      },
      {
        group_name: "1.5 ventricular repair DIRV 1",
        prior_group: "",
        group_id: "36.3",
        codes: [["1.5 ventricle repair"], ["Cavopulmonary anastomosis"]],
        concomitant_procedures: [
          "ASD creation or enlargement",
          "Pulmonary artery ligation or division",
          "Pulmonary artery dilation",
        ],
        subgroups: [],
      },
      {
        group_name: "Single ventricular repair DIRV 1",
        prior_group: "",
        group_id: "36.4",
        codes: [["Fontan"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "Fontan",
      "Stage 1 palliation",
      "Pulmonary artery ligation or division",
      "Systemic-to-pulmonary artery shunt",
      "IAA repair",
      "Pulmonary artery dilation",
      "Sano:RV to PA conduit",
      "Main pulmonary arterial banding",
      "Bilateral pulmonary arterial banding",
      "BTS:Blalock-Taussig shunt",
      "RV to PA conduit",
      "1.5 ventricle repair",
      "Hybrid stage 1 palliation",
      "Aortic arch repair",
      "Cavopulmonary anastomosis",
      "Aortopulmonary anastomosis",
      "PDA closure",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aortic commissure abnormality",
    native_disease_id: 37,
    groups: [
      {
        group_name: "Biventricular Aortic commissure abnormality 1",
        prior_group: "",
        group_id: "37.1",
        codes: [
          ["Aortic valve replacement"],
          ["Aortic root replacement"],
          ["Ascending aortic replacement"],
          ["Ross procedure"],
          ["Aortic valvuloplasty"],
        ],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Aortic root replacement",
      "Ross procedure",
      "Ascending aortic replacement",
      "Aortic valve replacement",
      "Aortic valvuloplasty",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "DOLV",
    native_disease_id: 38,
    groups: [
      {
        group_name: "Biventricular repair",
        prior_group: "",
        group_id: "38.1",
        codes: [["Rastelli procedure"]],
        concomitant_procedures: [],
        subgroups: [],
      },
      {
        group_name: "Palliative DOLV 1",
        prior_group: "",
        group_id: "38.2",
        codes: [
          ["Stage 1 palliation"],
          ["Systemic-to-pulmonary artery shunt"],
          ["Hybrid stage 1 palliation"],
          ["Main pulmonary arterial banding"],
          ["Bilateral pulmonary arterial banding"],
          ["Aortopulmonary anastomosis"],
          ["RV to PA conduit"],
        ],
        concomitant_procedures: [
          "IAA repair",
          "Aortic arch repair",
          "PDA closure",
          "RV to PA conduit",
        ],
        subgroups: [
          {
            subgroup_name: "Sano:RV to PA conduit",
            codes: [["Sano:RV to PA conduit"]],
          },
          {
            subgroup_name: "BTS:Blalock-Taussig shunt",
            codes: [["BTS:Blalock-Taussig shunt"]],
          },
          {
            subgroup_name: "Hybrid",
            codes: [["Hybrid stage 1 palliation"]],
          },
        ],
      },
      {
        group_name: "1.5 ventricular repair DOLV 1",
        prior_group: "",
        group_id: "38.3",
        codes: [["1.5 ventricle repair"], ["Cavopulmonary anastomosis"]],
        concomitant_procedures: [
          "ASD creation or enlargement",
          "Pulmonary artery ligation or division",
          "Pulmonary artery dilation",
        ],
        subgroups: [],
      },
      {
        group_name: "Single ventricular repair DOLV 1",
        prior_group: "",
        group_id: "38.4",
        codes: [["Fontan"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "ASD creation or enlargement",
      "Fontan",
      "Stage 1 palliation",
      "Pulmonary artery ligation or division",
      "Systemic-to-pulmonary artery shunt",
      "IAA repair",
      "Pulmonary artery dilation",
      "Sano:RV to PA conduit",
      "Rastelli procedure",
      "Main pulmonary arterial banding",
      "Bilateral pulmonary arterial banding",
      "BTS:Blalock-Taussig shunt",
      "RV to PA conduit",
      "1.5 ventricle repair",
      "Hybrid stage 1 palliation",
      "Aortic arch repair",
      "Cavopulmonary anastomosis",
      "Aortopulmonary anastomosis",
      "PDA closure",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Atrial septum - Aneurysm of septum primum",
    native_disease_id: 39,
    groups: [
      {
        group_name: "Biventricular Atrial septum - Aneurysm of septum primum 1",
        prior_group: "",
        group_id: "39.1",
        codes: [["ASD closure"]],
        concomitant_procedures: [],
        subgroups: [],
      },
    ],
    disease_related_procedures: ["ASD closure"],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "Aorta - CoA",
    native_disease_id: 40,
    groups: [
      {
        group_name: "Biventricular repair-Aorta-CoA Mild 1",
        prior_group: "",
        group_id: "40.1",
        codes: [
          ["VSD closure"],
          ["Coarctation procedure"],
          ["Aortic arch repair"],
          ["Coarctation procedure - Stent implantation"],
        ],
        concomitant_procedures: [
          "LVOT reconstruction",
          "VSD closure",
          "Mitral valvuloplasty",
          "Aortic valvuloplasty",
          "PDA closure",
          "Aortic annulus enlargment or augmentation",
        ],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "Coarctation procedure",
      "LVOT reconstruction",
      "PDA closure",
      "Aortic arch repair",
      "Mitral valvuloplasty",
      "Aortic valvuloplasty",
      "VSD closure",
      "Aortic annulus enlargment or augmentation",
      "Coarctation procedure - Stent implantation",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
  {
    native_disease: "ASD",
    native_disease_id: 41,
    groups: [
      {
        group_name: "Biventricular ASD 1",
        prior_group: "",
        group_id: "41.1",
        codes: [["ASD closure"], ["ASD closure - Sinus venosus septal defect repair"]],
        concomitant_procedures: ["PAPVC repair"],
        subgroups: [],
      },
    ],
    disease_related_procedures: [
      "PAPVC repair",
      "ASD closure",
      "ASD closure - Sinus venosus septal defect repair",
    ],
    outcome_procedures: [
      "ICD generator implantation",
      "Heart transplant",
      "Pacemaker, ICD, or loop recorder procedure",
      "Extracorporeal membrane oxygenator cannulation",
      "c",
    ],
  },
];

let ANATOMY_LIST = [];
let ANATOMY_TO_CODES_DICT = {};
let PRIOR_GROUP_TO_CODES_DICT = {};

DIAGNOSIS_GROUP_JSON.forEach((element) => {
  ANATOMY_LIST.push(element.native_disease);
  ANATOMY_TO_CODES_DICT[element.native_disease] = {};
  PRIOR_GROUP_TO_CODES_DICT[element.native_disease] = {};
  element.groups.forEach((group) => {
    if (group.group_name) {
      ANATOMY_TO_CODES_DICT[element.native_disease][group.group_name] = group.codes;

      let prior_group = group.prior_group;
      if (prior_group in PRIOR_GROUP_TO_CODES_DICT[element.native_disease]) {
        PRIOR_GROUP_TO_CODES_DICT[element.native_disease][prior_group][group.group_name] = group.codes;
      } else {
        PRIOR_GROUP_TO_CODES_DICT[element.native_disease][prior_group] = {};
        PRIOR_GROUP_TO_CODES_DICT[element.native_disease][prior_group][group.group_name] = group.codes;
      }
    }
  });
});
// console.log('ANATOMY_LIST :>> ', ANATOMY_LIST);
// console.log("ANATOMY_TO_CODES_DICT :>> ", ANATOMY_TO_CODES_DICT);
// console.log('PRIOR_GROUP_TO_CODES_DICT :>> ', PRIOR_GROUP_TO_CODES_DICT);
module.exports = {
  DIAGNOSIS_GROUP_JSON,
  ANATOMY_LIST,
  ANATOMY_TO_CODES_DICT,
  PRIOR_GROUP_TO_CODES_DICT,
};
