@startuml db-api-frontend
package "TWIST FRONT END" {
  [Nutrition Table] -- [Nutrition Volume]
  [Nutrition Table] -- [Nutrition fat-pro-cho]
  [Nutrition Table] -- [Nutrition Calories]

  [I/O Table] -- [I/O stack bar]
  [I/O Table] -- [I/O modal]

  [Medications]
}

package "TWIST API" {
  [TPN_LIPID] -down- dbConnector
  [EN] -down- dbConnector
  [TPN] -down- dbConnector
  [INTAKE_OUTPUT] -down- dbConnector
  [DRUG_INTERMITTENT] -down- dbConnector
  [DRUG_DILUENTS] -down- dbConnector
}

database DWTST

[Nutrition Volume] <-- [TPN_LIPID]
[Nutrition Volume] <-- [TPN]
[Nutrition Volume] <-- [EN]
[Nutrition Volume] <-- [INTAKE_OUTPUT]
[Nutrition Volume] <-- [DRUG_INTERMITTENT]
[Nutrition Volume] <-- [DRUG_DILUENTS]

[Nutrition fat-pro-cho] <-- [TPN_LIPID]
[Nutrition fat-pro-cho] <-- [TPN]
[Nutrition fat-pro-cho] <-- [EN]
[Nutrition fat-pro-cho] <-- [DRUG_DILUENTS]

[Nutrition Calories] <-- [TPN_LIPID]
[Nutrition Calories] <-- [TPN]
[Nutrition Calories] <-- [EN]
[Nutrition Calories] <-- [DRUG_DILUENTS]

[I/O stack bar] <-- [TPN]
[I/O stack bar] <-- [TPN_LIPID]
[I/O stack bar] <-- [EN]
[I/O stack bar] <-- [INTAKE_OUTPUT]
[I/O stack bar] <-- [DRUG_DILUENTS]

[I/O modal] <-- [TPN]
[I/O modal] <-- [TPN_LIPID]
[I/O modal] <-- [EN]
[I/O modal] <-- [INTAKE_OUTPUT]
[I/O modal] <-- [DRUG_DILUENTS]

[I/O stack bar] <-- [TPN]
[I/O stack bar] <-- [EN]
[I/O stack bar] <-- [INTAKE_OUTPUT]
[I/O stack bar] <-- [DRUG_DILUENTS]

[Medications] <-- [DRUG_INTERMITTENT]

DWTST -up- dbConnector
@enduml