@startuml db-api-frontend

' skinparam componentStyle uml2
' left to right direction

package "TWIST FRONT END" as frontend #f1f8e9 {
    frame "log in page" as login {
        [Auth] -right- [MRN input]
    }

    frame "main page" as main {
        [RSS]
        [Body Container] -- [I/O Table]
        [Body Container] -- [Nutrition Table]
        [Body Container] -- [Medications]
        [Body Container] -- [Vitals]
        [Nutrition Table] -- [Nutrition Volume]
        [Nutrition Table] -- [Nutrition Fat-Pro-Cho]
        [Nutrition Table] -- [Nutrition Calories]
        [I/O Table] -- [I/O stack bar]
        [I/O Table] -- [I/O modal]
    }
  
    main -[hidden]up- login
}

package "TWIST API" as api #e0f7fa {
    frame interface {
        interface "fat-pro-cho" as fpc
        interface volume
        interface "inout-tooltip" as iot
        interface inout
        interface med
        interface apiRSS
        interface apiVitals
        interface calories
        interface others
    }
    
    frame "fetch middleware" as fm {
        interface "Initial Fetch" as firstFetch
        interface "Interface fetch" as IfFetch
        firstFetch -[hidden]up- IfFetch
    }

    database Redis #fbe9e7 {
        [Cache]
    }
    
    frame "single table fetch" as stf {
        [TPN_LIPID]
        [EN]
        [TPN]
        [INTAKE_OUTPUT]
        [DRUG_INTERMITTENT]
        [DRUG_DILUENTS]
    }

    fm -[hidden]up- interface
    Redis -[hidden]down- stf
    firstFetch .right.> stf: if no cache 
    firstFetch .down.> [Cache] :if has cache
    stf -[hidden]up- firstFetch
    stf =up=> [Cache]
    IfFetch <=down=> [Cache]
    IfFetch <=up=> interface

    [TPN_LIPID] -- dbConnector
    [EN] -- dbConnector
    [TPN] -- dbConnector
    [INTAKE_OUTPUT] -- dbConnector
    [DRUG_INTERMITTENT] -- dbConnector
    [DRUG_DILUENTS] -- dbConnector
}
    
database DWTST #fbe9e7

[MRN input] --> firstFetch
[Nutrition Fat-Pro-Cho] <--> fpc
[Nutrition Calories] <--> calories
[Nutrition Volume] <--> volume
[I/O stack bar] <--> inout
[I/O modal] <--> iot
[Medications] <--> med
[RSS] <--> apiRSS
[Vitals] <--> apiVitals

DWTST -up- dbConnector
frontend -[hidden]down- api

@enduml