@startuml flow chart
:git clone https://github.com/TwistTRL/nodejs-twist-api.git;
:cd nodejs-twist-api/;
:npm install;

split
  :npm run devdocs;
  note left
  dev
  end note
  :npm run dev;
  note left
    nodemon
  end note
split again
  :npm test;
  note right
    mocha
  end note
  stop
split again
  : npm run docs;
  note right
    production
  end note
  :npm start;
  note right
    pm2
  end note
end split

:twist:3333/api/|
note right
  open in web browser
end note
@enduml