@startuml sequence

actor User

== Authentication (log in page) ==
User -> "Server 4000": Sign in
activate "Server 4000"
"Server 4000" -> "API 3333": Sign in API
activate "API 3333"
note right of "API 3333"
authentication
server
end note
"Server 4000" <-- "API 3333": Access token
deactivate "API 3333"
User <-- "Server 4000": Signed in

deactivate "Server 4000"

== Initial (census page) ==

User -> "Server 4000": Input/Select MRN
activate "Server 4000"
"Server 4000" -> "API 3333": Initial API fetch
activate "API 3333"

"API 3333" -> Database: fetch multiple tables
activate Database
Database -> Redis: save cache
deactivate Database 

activate Redis
note right of Redis
combine multiple
tables data
end note
"API 3333" <-- Redis
deactivate Redis

"Server 4000" <-- "API 3333": Initial fetch finished
deactivate "API 3333"

User <-- "Server 4000": Response
deactivate "Server 4000"

== Resource (single patient page) ==

User -> "Server 4000": Request
activate "Server 4000"
"Server 4000" -> "API 3333":
activate "API 3333"
"API 3333" -> Redis: if has cache
activate Redis
"API 3333" <-- Redis
deactivate Redis
"API 3333" -> Database: if no cache
activate Database
"API 3333" <-- Database
deactivate Database
"Server 4000" <-- "API 3333":

deactivate "API 3333"
User <-- "Server 4000": Response
deactivate "Server 4000"

@enduml